// Mocks generated by Mockito 5.4.6 from annotations
// in studify/test/presentation/screens/home/home_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:studify/data/models/class_schedule_model.dart' as _i3;
import 'package:studify/data/models/classroom_model.dart' as _i2;
import 'package:studify/data/models/combined_schedule_model.dart' as _i6;
import 'package:studify/data/models/notification_model.dart' as _i12;
import 'package:studify/data/models/personal_schedule_model.dart' as _i4;
import 'package:studify/data/services/device_token_service.dart' as _i14;
import 'package:studify/providers/auth_provider.dart' as _i9;
import 'package:studify/providers/classroom_provider.dart' as _i10;
import 'package:studify/providers/combined_schedule_provider.dart' as _i5;
import 'package:studify/providers/notification_provider.dart' as _i11;
import 'package:studify/providers/personal_schedule_provider.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClassroom_0 extends _i1.SmartFake implements _i2.Classroom {
  _FakeClassroom_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClassSchedule_1 extends _i1.SmartFake implements _i3.ClassSchedule {
  _FakeClassSchedule_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePersonalSchedule_2 extends _i1.SmartFake
    implements _i4.PersonalSchedule {
  _FakePersonalSchedule_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CombinedScheduleProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockCombinedScheduleProvider extends _i1.Mock
    implements _i5.CombinedScheduleProvider {
  MockCombinedScheduleProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i6.CombinedSchedule> get schedules =>
      (super.noSuchMethod(
            Invocation.getter(#schedules),
            returnValue: <_i6.CombinedSchedule>[],
          )
          as List<_i6.CombinedSchedule>);

  @override
  List<_i6.ScheduleSource> get availableSources =>
      (super.noSuchMethod(
            Invocation.getter(#availableSources),
            returnValue: <_i6.ScheduleSource>[],
          )
          as List<_i6.ScheduleSource>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.Future<void> fetchCombinedSchedules({
    String? source,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCombinedSchedules, [], {
              #source: source,
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> refresh({DateTime? startDate, DateTime? endDate}) =>
      (super.noSuchMethod(
            Invocation.method(#refresh, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void clear() => super.noSuchMethod(
    Invocation.method(#clear, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i9.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.AuthStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i9.AuthStatus.initial,
          )
          as _i9.AuthStatus);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.Future<void> checkAuthStatus() =>
      (super.noSuchMethod(
            Invocation.method(#checkAuthStatus, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> register({
    required String? name,
    required String? email,
    required String? password,
    required String? passwordConfirmation,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #name: name,
              #email: email,
              #password: password,
              #passwordConfirmation: passwordConfirmation,
            }),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> login({required String? email, required String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> updateProfile({required String? name}) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {#name: name}),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ClassroomProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassroomProvider extends _i1.Mock implements _i10.ClassroomProvider {
  MockClassroomProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Classroom> get classrooms =>
      (super.noSuchMethod(
            Invocation.getter(#classrooms),
            returnValue: <_i2.Classroom>[],
          )
          as List<_i2.Classroom>);

  @override
  List<_i3.ClassSchedule> get schedules =>
      (super.noSuchMethod(
            Invocation.getter(#schedules),
            returnValue: <_i3.ClassSchedule>[],
          )
          as List<_i3.ClassSchedule>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.Future<void> fetchClassrooms() =>
      (super.noSuchMethod(
            Invocation.method(#fetchClassrooms, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> fetchClassroom(int? classroomId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchClassroom, [classroomId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.Classroom> createClassroom({
    required String? name,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createClassroom, [], {
              #name: name,
              #description: description,
            }),
            returnValue: _i7.Future<_i2.Classroom>.value(
              _FakeClassroom_0(
                this,
                Invocation.method(#createClassroom, [], {
                  #name: name,
                  #description: description,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.Classroom>);

  @override
  _i7.Future<_i2.Classroom> joinClassroom(String? uniqueCode) =>
      (super.noSuchMethod(
            Invocation.method(#joinClassroom, [uniqueCode]),
            returnValue: _i7.Future<_i2.Classroom>.value(
              _FakeClassroom_0(
                this,
                Invocation.method(#joinClassroom, [uniqueCode]),
              ),
            ),
          )
          as _i7.Future<_i2.Classroom>);

  @override
  _i7.Future<void> fetchClassSchedules(
    int? classroomId, {
    bool? notify = true,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchClassSchedules,
              [classroomId],
              {#notify: notify, #startDate: startDate, #endDate: endDate},
            ),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i3.ClassSchedule> createClassSchedule({
    required int? classroomId,
    required String? title,
    required DateTime? startTime,
    required DateTime? endTime,
    String? location,
    String? lecturer,
    String? description,
    String? color,
    int? coordinator1,
    int? coordinator2,
    List<int>? repeatDays,
    int? repeatCount,
    List<int>? reminders,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createClassSchedule, [], {
              #classroomId: classroomId,
              #title: title,
              #startTime: startTime,
              #endTime: endTime,
              #location: location,
              #lecturer: lecturer,
              #description: description,
              #color: color,
              #coordinator1: coordinator1,
              #coordinator2: coordinator2,
              #repeatDays: repeatDays,
              #repeatCount: repeatCount,
              #reminders: reminders,
            }),
            returnValue: _i7.Future<_i3.ClassSchedule>.value(
              _FakeClassSchedule_1(
                this,
                Invocation.method(#createClassSchedule, [], {
                  #classroomId: classroomId,
                  #title: title,
                  #startTime: startTime,
                  #endTime: endTime,
                  #location: location,
                  #lecturer: lecturer,
                  #description: description,
                  #color: color,
                  #coordinator1: coordinator1,
                  #coordinator2: coordinator2,
                  #repeatDays: repeatDays,
                  #repeatCount: repeatCount,
                  #reminders: reminders,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.ClassSchedule>);

  @override
  _i7.Future<_i3.ClassSchedule> updateClassSchedule({
    required int? classroomId,
    required int? scheduleId,
    String? title,
    DateTime? startTime,
    DateTime? endTime,
    String? location,
    String? lecturer,
    String? description,
    String? color,
    int? coordinator1,
    int? coordinator2,
    List<int>? reminders,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateClassSchedule, [], {
              #classroomId: classroomId,
              #scheduleId: scheduleId,
              #title: title,
              #startTime: startTime,
              #endTime: endTime,
              #location: location,
              #lecturer: lecturer,
              #description: description,
              #color: color,
              #coordinator1: coordinator1,
              #coordinator2: coordinator2,
              #reminders: reminders,
            }),
            returnValue: _i7.Future<_i3.ClassSchedule>.value(
              _FakeClassSchedule_1(
                this,
                Invocation.method(#updateClassSchedule, [], {
                  #classroomId: classroomId,
                  #scheduleId: scheduleId,
                  #title: title,
                  #startTime: startTime,
                  #endTime: endTime,
                  #location: location,
                  #lecturer: lecturer,
                  #description: description,
                  #color: color,
                  #coordinator1: coordinator1,
                  #coordinator2: coordinator2,
                  #reminders: reminders,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.ClassSchedule>);

  @override
  _i7.Future<void> deleteClassSchedule({
    required int? classroomId,
    required int? scheduleId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteClassSchedule, [], {
              #classroomId: classroomId,
              #scheduleId: scheduleId,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> leaveClassroom(int? classroomId) =>
      (super.noSuchMethod(
            Invocation.method(#leaveClassroom, [classroomId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> removeMember({
    required int? classroomId,
    required int? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeMember, [], {
              #classroomId: classroomId,
              #userId: userId,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> transferOwnership({
    required int? classroomId,
    required int? newOwnerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#transferOwnership, [], {
              #classroomId: classroomId,
              #newOwnerId: newOwnerId,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateClassroomDescription({
    required int? classroomId,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateClassroomDescription, [], {
              #classroomId: classroomId,
              #description: description,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearSchedules() => super.noSuchMethod(
    Invocation.method(#clearSchedules, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NotificationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationProvider extends _i1.Mock
    implements _i11.NotificationProvider {
  MockNotificationProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i12.NotificationModel> get notifications =>
      (super.noSuchMethod(
            Invocation.getter(#notifications),
            returnValue: <_i12.NotificationModel>[],
          )
          as List<_i12.NotificationModel>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  int get unreadCount =>
      (super.noSuchMethod(Invocation.getter(#unreadCount), returnValue: 0)
          as int);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.Future<void> fetchNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#fetchNotifications, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> markAsRead(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> markAllRead() =>
      (super.noSuchMethod(
            Invocation.method(#markAllRead, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PersonalScheduleProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonalScheduleProvider extends _i1.Mock
    implements _i13.PersonalScheduleProvider {
  MockPersonalScheduleProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i4.PersonalSchedule> get schedules =>
      (super.noSuchMethod(
            Invocation.getter(#schedules),
            returnValue: <_i4.PersonalSchedule>[],
          )
          as List<_i4.PersonalSchedule>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i7.Future<void> fetchPersonalSchedules() =>
      (super.noSuchMethod(
            Invocation.method(#fetchPersonalSchedules, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i4.PersonalSchedule> createPersonalSchedule({
    required String? title,
    required DateTime? startTime,
    required DateTime? endTime,
    String? location,
    String? description,
    required String? color,
    List<int>? reminders,
    List<int>? repeatDays,
    int? repeatCount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPersonalSchedule, [], {
              #title: title,
              #startTime: startTime,
              #endTime: endTime,
              #location: location,
              #description: description,
              #color: color,
              #reminders: reminders,
              #repeatDays: repeatDays,
              #repeatCount: repeatCount,
            }),
            returnValue: _i7.Future<_i4.PersonalSchedule>.value(
              _FakePersonalSchedule_2(
                this,
                Invocation.method(#createPersonalSchedule, [], {
                  #title: title,
                  #startTime: startTime,
                  #endTime: endTime,
                  #location: location,
                  #description: description,
                  #color: color,
                  #reminders: reminders,
                  #repeatDays: repeatDays,
                  #repeatCount: repeatCount,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.PersonalSchedule>);

  @override
  _i7.Future<_i4.PersonalSchedule> updatePersonalSchedule({
    required int? scheduleId,
    String? title,
    DateTime? startTime,
    DateTime? endTime,
    String? location,
    String? description,
    String? color,
    List<int>? reminders,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePersonalSchedule, [], {
              #scheduleId: scheduleId,
              #title: title,
              #startTime: startTime,
              #endTime: endTime,
              #location: location,
              #description: description,
              #color: color,
              #reminders: reminders,
            }),
            returnValue: _i7.Future<_i4.PersonalSchedule>.value(
              _FakePersonalSchedule_2(
                this,
                Invocation.method(#updatePersonalSchedule, [], {
                  #scheduleId: scheduleId,
                  #title: title,
                  #startTime: startTime,
                  #endTime: endTime,
                  #location: location,
                  #description: description,
                  #color: color,
                  #reminders: reminders,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.PersonalSchedule>);

  @override
  _i7.Future<void> deletePersonalSchedule(int? scheduleId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePersonalSchedule, [scheduleId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DeviceTokenService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceTokenService extends _i1.Mock
    implements _i14.DeviceTokenService {
  MockDeviceTokenService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<String?> getDeviceToken() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceToken, []),
            returnValue: _i7.Future<String?>.value(),
          )
          as _i7.Future<String?>);

  @override
  _i7.Future<void> syncDeviceToken() =>
      (super.noSuchMethod(
            Invocation.method(#syncDeviceToken, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
