// Mocks generated by Mockito 5.4.6 from annotations
// in studify/test/unit/widgets/class_schedule_detail_sheet_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:studify/data/models/class_schedule_model.dart' as _i3;
import 'package:studify/data/models/classroom_model.dart' as _i2;
import 'package:studify/providers/auth_provider.dart' as _i4;
import 'package:studify/providers/classroom_provider.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClassroom_0 extends _i1.SmartFake implements _i2.Classroom {
  _FakeClassroom_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClassSchedule_1 extends _i1.SmartFake implements _i3.ClassSchedule {
  _FakeClassSchedule_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i4.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AuthStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i4.AuthStatus.initial,
          )
          as _i4.AuthStatus);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> checkAuthStatus() =>
      (super.noSuchMethod(
            Invocation.method(#checkAuthStatus, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> register({
    required String? name,
    required String? email,
    required String? password,
    required String? passwordConfirmation,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #name: name,
              #email: email,
              #password: password,
              #passwordConfirmation: passwordConfirmation,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> login({required String? email, required String? password}) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ClassroomProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassroomProvider extends _i1.Mock implements _i7.ClassroomProvider {
  MockClassroomProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.Classroom> get classrooms =>
      (super.noSuchMethod(
            Invocation.getter(#classrooms),
            returnValue: <_i2.Classroom>[],
          )
          as List<_i2.Classroom>);

  @override
  List<_i3.ClassSchedule> get schedules =>
      (super.noSuchMethod(
            Invocation.getter(#schedules),
            returnValue: <_i3.ClassSchedule>[],
          )
          as List<_i3.ClassSchedule>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i5.Future<void> fetchClassrooms() =>
      (super.noSuchMethod(
            Invocation.method(#fetchClassrooms, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> fetchClassroom(int? classroomId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchClassroom, [classroomId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.Classroom> createClassroom({
    required String? name,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createClassroom, [], {
              #name: name,
              #description: description,
            }),
            returnValue: _i5.Future<_i2.Classroom>.value(
              _FakeClassroom_0(
                this,
                Invocation.method(#createClassroom, [], {
                  #name: name,
                  #description: description,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Classroom>);

  @override
  _i5.Future<_i2.Classroom> joinClassroom(String? uniqueCode) =>
      (super.noSuchMethod(
            Invocation.method(#joinClassroom, [uniqueCode]),
            returnValue: _i5.Future<_i2.Classroom>.value(
              _FakeClassroom_0(
                this,
                Invocation.method(#joinClassroom, [uniqueCode]),
              ),
            ),
          )
          as _i5.Future<_i2.Classroom>);

  @override
  _i5.Future<void> fetchClassSchedules(int? classroomId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchClassSchedules, [classroomId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i3.ClassSchedule> createClassSchedule({
    required int? classroomId,
    required String? title,
    required DateTime? startTime,
    required DateTime? endTime,
    String? location,
    String? lecturer,
    String? description,
    String? color,
    int? coordinator1,
    int? coordinator2,
    List<int>? repeatDays,
    int? repeatCount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createClassSchedule, [], {
              #classroomId: classroomId,
              #title: title,
              #startTime: startTime,
              #endTime: endTime,
              #location: location,
              #lecturer: lecturer,
              #description: description,
              #color: color,
              #coordinator1: coordinator1,
              #coordinator2: coordinator2,
              #repeatDays: repeatDays,
              #repeatCount: repeatCount,
            }),
            returnValue: _i5.Future<_i3.ClassSchedule>.value(
              _FakeClassSchedule_1(
                this,
                Invocation.method(#createClassSchedule, [], {
                  #classroomId: classroomId,
                  #title: title,
                  #startTime: startTime,
                  #endTime: endTime,
                  #location: location,
                  #lecturer: lecturer,
                  #description: description,
                  #color: color,
                  #coordinator1: coordinator1,
                  #coordinator2: coordinator2,
                  #repeatDays: repeatDays,
                  #repeatCount: repeatCount,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.ClassSchedule>);

  @override
  _i5.Future<_i3.ClassSchedule> updateClassSchedule({
    required int? classroomId,
    required int? scheduleId,
    String? title,
    DateTime? startTime,
    DateTime? endTime,
    String? location,
    String? lecturer,
    String? description,
    String? color,
    int? coordinator1,
    int? coordinator2,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateClassSchedule, [], {
              #classroomId: classroomId,
              #scheduleId: scheduleId,
              #title: title,
              #startTime: startTime,
              #endTime: endTime,
              #location: location,
              #lecturer: lecturer,
              #description: description,
              #color: color,
              #coordinator1: coordinator1,
              #coordinator2: coordinator2,
            }),
            returnValue: _i5.Future<_i3.ClassSchedule>.value(
              _FakeClassSchedule_1(
                this,
                Invocation.method(#updateClassSchedule, [], {
                  #classroomId: classroomId,
                  #scheduleId: scheduleId,
                  #title: title,
                  #startTime: startTime,
                  #endTime: endTime,
                  #location: location,
                  #lecturer: lecturer,
                  #description: description,
                  #color: color,
                  #coordinator1: coordinator1,
                  #coordinator2: coordinator2,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.ClassSchedule>);

  @override
  _i5.Future<void> deleteClassSchedule({
    required int? classroomId,
    required int? scheduleId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteClassSchedule, [], {
              #classroomId: classroomId,
              #scheduleId: scheduleId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> leaveClassroom(int? classroomId) =>
      (super.noSuchMethod(
            Invocation.method(#leaveClassroom, [classroomId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeMember({
    required int? classroomId,
    required int? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeMember, [], {
              #classroomId: classroomId,
              #userId: userId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> transferOwnership({
    required int? classroomId,
    required int? newOwnerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#transferOwnership, [], {
              #classroomId: classroomId,
              #newOwnerId: newOwnerId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateClassroomDescription({
    required int? classroomId,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateClassroomDescription, [], {
              #classroomId: classroomId,
              #description: description,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearSchedules() => super.noSuchMethod(
    Invocation.method(#clearSchedules, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
