// Mocks generated by Mockito 5.4.6 from annotations
// in studify/test/unit/deep_link_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:app_links/src/app_links.dart' as _i2;
import 'package:flutter/src/widgets/navigator.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AppLinks].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppLinks extends _i1.Mock implements _i2.AppLinks {
  MockAppLinks() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<String> get stringLinkStream =>
      (super.noSuchMethod(
            Invocation.getter(#stringLinkStream),
            returnValue: _i3.Stream<String>.empty(),
          )
          as _i3.Stream<String>);

  @override
  _i3.Stream<Uri> get uriLinkStream =>
      (super.noSuchMethod(
            Invocation.getter(#uriLinkStream),
            returnValue: _i3.Stream<Uri>.empty(),
          )
          as _i3.Stream<Uri>);

  @override
  _i3.Future<Uri?> getInitialLink() =>
      (super.noSuchMethod(
            Invocation.method(#getInitialLink, []),
            returnValue: _i3.Future<Uri?>.value(),
          )
          as _i3.Future<Uri?>);

  @override
  _i3.Future<String?> getInitialLinkString() =>
      (super.noSuchMethod(
            Invocation.method(#getInitialLinkString, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<Uri?> getLatestLink() =>
      (super.noSuchMethod(
            Invocation.method(#getLatestLink, []),
            returnValue: _i3.Future<Uri?>.value(),
          )
          as _i3.Future<Uri?>);

  @override
  _i3.Future<String?> getLatestLinkString() =>
      (super.noSuchMethod(
            Invocation.method(#getLatestLinkString, []),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}

/// A class which mocks [NavigatorObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigatorObserver extends _i1.Mock implements _i4.NavigatorObserver {
  @override
  void didPush(_i4.Route<dynamic>? route, _i4.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPush, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didPop(_i4.Route<dynamic>? route, _i4.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
        Invocation.method(#didPop, [route, previousRoute]),
        returnValueForMissingStub: null,
      );

  @override
  void didRemove(
    _i4.Route<dynamic>? route,
    _i4.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didRemove, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didReplace({
    _i4.Route<dynamic>? newRoute,
    _i4.Route<dynamic>? oldRoute,
  }) => super.noSuchMethod(
    Invocation.method(#didReplace, [], {
      #newRoute: newRoute,
      #oldRoute: oldRoute,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void didChangeTop(
    _i4.Route<dynamic>? topRoute,
    _i4.Route<dynamic>? previousTopRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didChangeTop, [topRoute, previousTopRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStartUserGesture(
    _i4.Route<dynamic>? route,
    _i4.Route<dynamic>? previousRoute,
  ) => super.noSuchMethod(
    Invocation.method(#didStartUserGesture, [route, previousRoute]),
    returnValueForMissingStub: null,
  );

  @override
  void didStopUserGesture() => super.noSuchMethod(
    Invocation.method(#didStopUserGesture, []),
    returnValueForMissingStub: null,
  );
}
