// Mocks generated by Mockito 5.4.6 from annotations
// in studify/test/integration/classroom_flow_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:studify/data/models/class_schedule_model.dart' as _i3;
import 'package:studify/data/models/classroom_model.dart' as _i2;
import 'package:studify/data/services/classroom_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClassroom_0 extends _i1.SmartFake implements _i2.Classroom {
  _FakeClassroom_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClassSchedule_1 extends _i1.SmartFake implements _i3.ClassSchedule {
  _FakeClassSchedule_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ClassroomService].
///
/// See the documentation for Mockito's code generation for more information.
class MockClassroomService extends _i1.Mock implements _i4.ClassroomService {
  MockClassroomService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.Classroom>> getClassrooms() =>
      (super.noSuchMethod(
            Invocation.method(#getClassrooms, []),
            returnValue: _i5.Future<List<_i2.Classroom>>.value(
              <_i2.Classroom>[],
            ),
          )
          as _i5.Future<List<_i2.Classroom>>);

  @override
  _i5.Future<_i2.Classroom> getClassroom(int? classroomId) =>
      (super.noSuchMethod(
            Invocation.method(#getClassroom, [classroomId]),
            returnValue: _i5.Future<_i2.Classroom>.value(
              _FakeClassroom_0(
                this,
                Invocation.method(#getClassroom, [classroomId]),
              ),
            ),
          )
          as _i5.Future<_i2.Classroom>);

  @override
  _i5.Future<_i2.Classroom> createClassroom({
    required String? name,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createClassroom, [], {
              #name: name,
              #description: description,
            }),
            returnValue: _i5.Future<_i2.Classroom>.value(
              _FakeClassroom_0(
                this,
                Invocation.method(#createClassroom, [], {
                  #name: name,
                  #description: description,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Classroom>);

  @override
  _i5.Future<_i2.Classroom> joinClassroom(String? uniqueCode) =>
      (super.noSuchMethod(
            Invocation.method(#joinClassroom, [uniqueCode]),
            returnValue: _i5.Future<_i2.Classroom>.value(
              _FakeClassroom_0(
                this,
                Invocation.method(#joinClassroom, [uniqueCode]),
              ),
            ),
          )
          as _i5.Future<_i2.Classroom>);

  @override
  _i5.Future<List<_i3.ClassSchedule>> getClassSchedules(
    int? classroomId, {
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getClassSchedules,
              [classroomId],
              {#startDate: startDate, #endDate: endDate},
            ),
            returnValue: _i5.Future<List<_i3.ClassSchedule>>.value(
              <_i3.ClassSchedule>[],
            ),
          )
          as _i5.Future<List<_i3.ClassSchedule>>);

  @override
  _i5.Future<_i3.ClassSchedule> createClassSchedule({
    required int? classroomId,
    required String? title,
    required DateTime? startTime,
    required DateTime? endTime,
    String? location,
    String? lecturer,
    String? description,
    String? color,
    int? coordinator1,
    int? coordinator2,
    List<int>? repeatDays,
    int? repeatCount,
    List<int>? reminders,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createClassSchedule, [], {
              #classroomId: classroomId,
              #title: title,
              #startTime: startTime,
              #endTime: endTime,
              #location: location,
              #lecturer: lecturer,
              #description: description,
              #color: color,
              #coordinator1: coordinator1,
              #coordinator2: coordinator2,
              #repeatDays: repeatDays,
              #repeatCount: repeatCount,
              #reminders: reminders,
            }),
            returnValue: _i5.Future<_i3.ClassSchedule>.value(
              _FakeClassSchedule_1(
                this,
                Invocation.method(#createClassSchedule, [], {
                  #classroomId: classroomId,
                  #title: title,
                  #startTime: startTime,
                  #endTime: endTime,
                  #location: location,
                  #lecturer: lecturer,
                  #description: description,
                  #color: color,
                  #coordinator1: coordinator1,
                  #coordinator2: coordinator2,
                  #repeatDays: repeatDays,
                  #repeatCount: repeatCount,
                  #reminders: reminders,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.ClassSchedule>);

  @override
  _i5.Future<_i3.ClassSchedule> updateClassSchedule({
    required int? classroomId,
    required int? scheduleId,
    String? title,
    DateTime? startTime,
    DateTime? endTime,
    String? location,
    String? lecturer,
    String? description,
    String? color,
    int? coordinator1,
    int? coordinator2,
    List<int>? reminders,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateClassSchedule, [], {
              #classroomId: classroomId,
              #scheduleId: scheduleId,
              #title: title,
              #startTime: startTime,
              #endTime: endTime,
              #location: location,
              #lecturer: lecturer,
              #description: description,
              #color: color,
              #coordinator1: coordinator1,
              #coordinator2: coordinator2,
              #reminders: reminders,
            }),
            returnValue: _i5.Future<_i3.ClassSchedule>.value(
              _FakeClassSchedule_1(
                this,
                Invocation.method(#updateClassSchedule, [], {
                  #classroomId: classroomId,
                  #scheduleId: scheduleId,
                  #title: title,
                  #startTime: startTime,
                  #endTime: endTime,
                  #location: location,
                  #lecturer: lecturer,
                  #description: description,
                  #color: color,
                  #coordinator1: coordinator1,
                  #coordinator2: coordinator2,
                  #reminders: reminders,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.ClassSchedule>);

  @override
  _i5.Future<void> deleteClassSchedule({
    required int? classroomId,
    required int? scheduleId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteClassSchedule, [], {
              #classroomId: classroomId,
              #scheduleId: scheduleId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> leaveClassroom(int? classroomId) =>
      (super.noSuchMethod(
            Invocation.method(#leaveClassroom, [classroomId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeMember({
    required int? classroomId,
    required int? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeMember, [], {
              #classroomId: classroomId,
              #userId: userId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> transferOwnership({
    required int? classroomId,
    required int? newOwnerId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#transferOwnership, [], {
              #classroomId: classroomId,
              #newOwnerId: newOwnerId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.Classroom> updateClassroomDescription({
    required int? classroomId,
    String? description,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateClassroomDescription, [], {
              #classroomId: classroomId,
              #description: description,
            }),
            returnValue: _i5.Future<_i2.Classroom>.value(
              _FakeClassroom_0(
                this,
                Invocation.method(#updateClassroomDescription, [], {
                  #classroomId: classroomId,
                  #description: description,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.Classroom>);

  @override
  _i5.Future<void> deleteClassroom(int? classroomId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteClassroom, [classroomId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
